# Generated by Django 3.2.8 on 2023-09-22 16:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=tinymce.models.HTMLField(),
        ),
    ]
